[project]
name = "open-agent-spec"
version = "0.1.0"
description = "Open Agent Spec CLI for bootstrapping ai agent projects"
authors = [{ name="Andrew Whitehouse", email="andrewswhitehouse@gmail.com" }]
license = "MIT"
readme = "README.md"
dependencies = [
    "typer[all]>=0.9.0",
    "pyyaml",
    "rich"
]

[project.scripts]
oas = "oas_cli.main:app"