name: Feature Branch Tests

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    concurrency:
      group: feature-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-html pydantic
          if [ -f requirements.txt ]; then pip install -r requirements.txt --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/; fi
          pip install ".[dev]"  # Install dev dependencies including linting tools
      - name: Run tests with comprehensive reporting
        run: |
          python -m pytest tests/ \
            -v \
            --tb=short \
            --junitxml=test-results.xml \
            --html=test-report.html \
            --self-contained-html \
            --cov=oas_cli \
            --cov-report=html \
            --cov-report=xml \
            --cov-report=term-missing
      
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-feature-branch
          path: |
            test-results.xml
            test-report.html
            htmlcov/
          retention-days: 7
      
      - name: Generate comprehensive test summary
        if: always()
        run: |
          echo "# 🧪 Open Agent Stack Framework Tests" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Framework Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Python Version:** 3.12" >> $GITHUB_STEP_SUMMARY
          echo "- **Engine Support:** OpenAI, Claude/Anthropic" >> $GITHUB_STEP_SUMMARY
          echo "- **Test Categories:** Contract validation, Agent generation, Multi-engine compatibility" >> $GITHUB_STEP_SUMMARY  
          echo "- **Behavioral Contracts:** ✅ Temperature control, Required fields, Safety checks" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Test Validation Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This validates that the Open Agent Stack framework correctly handles:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Multi-engine agent generation**" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Behavioral contract enforcement**" >> $GITHUB_STEP_SUMMARY  
          echo "- ✅ **YAML specification validation**" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Cross-platform compatibility**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Detailed Reports" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 **Coverage Report:** \`htmlcov/index.html\`" >> $GITHUB_STEP_SUMMARY
          echo "- 📋 **HTML Test Report:** \`test-report.html\`" >> $GITHUB_STEP_SUMMARY
          echo "- 📄 **JUnit XML:** \`test-results.xml\`" >> $GITHUB_STEP_SUMMARY
      - name: Run code quality checks
        run: |
          flake8 . --max-line-length=100 --ignore=E501,W503,E203 --exclude=test_output/
          ruff check . --exclude test_output/
          ruff format . --exclude test_output/
          mypy oas_cli tests
