name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install core dependencies from main PyPI
        pip install pytest pytest-cov pydantic>=2.0.0
        # Install behavioral-contracts from TestPyPI
        pip install --index-url https://test.pypi.org/simple/ --no-deps behavioral-contracts
        # Then install project dependencies
        pip install -e .
    
    - name: Run tests
      run: |
        pytest tests/ --cov=oas_cli --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 